### ISSUE TITLE
Attempt basic integration with Jupyter (IPython) Notebooks

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/tree-illustrator#10]
Here are two shared notebooks (links are to a _read-only nbviewer!_) that test the notion of a "static" (JS-only) widget for the Tree Illustrator. The [editable .ipynb files](https://github.com/OpenTreeOfLife/tree-illustrator/tree/master/ipython) in this repo should work properly from a local server and show nicer results.

In early experiments, [I tried a few different approaches](http://nbviewer.ipython.org/github/OpenTreeOfLife/tree-illustrator/blob/master/ipython/embedding-tree-illustrator-experiments.ipynb) to embedding one (or more) Tree Illustrator instances in the notebook.

I would prefer a [JS-only widget, enabled via a simple module](http://nbviewer.ipython.org/github/OpenTreeOfLife/tree-illustrator/blob/master/ipython/tree-illustrator-widget-testbed.ipynb), but it seems an IPython notebook doesn't provide the same access to its cells as we get in an interactive notebook.

Still, it's progress. The remaining work on an API (between the Illustrator IFRAME and the surrounding page) is actually straightforward, and should allow us to pass tree and other data into the Illustrator UI
and retrieve SVG output or full illustration JSON.

**Comment by jimallman** [comment]
Incidentally, I can return to the original experiment of making a subclass in IPython. I was shooting for a JS-only widget for a couple of reasons. I actually thought it would be more robust in a read-only notebook viewer, but it seems I'm swimming upstream there. More importantly, I was looking for a solution that would work on any existing notebook server. If we use the (apparently more robust) server-side widget, it will need to be accepted into the jupyter/notebook repo (and Wakari, etc.) and discovered by users.

@rhr, what do suppose are the most common scenarios (and tools) for sharing notebooks? Should I assume that researchers would be running a local notebook server and truly interactive notebooks? I assume this is done by handing the file back and forth, since there's no real-time collaboration feature a la Google Docs, correct?

(Incidentally, I did see that [SageMathCloud](http://sagemath.blogspot.com/2013/09/ipython-notebooks-in-cloud-with.html) is working on this now, but their sync'ing strategy will not extend to our Tree Illustrator mega-widget unless we somehow broadcast every gesture and action in its UI.)

**Comment by rhr** [comment]
Wow, that is pretty cool stuff. I think a local notebook server, and sharing notebook links or files, is a safe default assumption for now. Real-time collaboration and syncing seems not worth pursuing at this stage.

With the IFRAME API you refer to, it will be possible to modify illustration parameters, and pull data from the illustrator, from the python side? That would be great!

**Comment by jimallman** [comment]
> With the IFRAME API you refer to, it will be possible to modify illustration parameters, and pull data from the illustrator, from the python side? That would be great!

We have solid communication between the IFRAME and the surrounding notebook page. It's all in Javascript at the moment, and it seems JS variables are limited to a single code cell (bummer). I just realized that JS and Python are blind to one another's variables, which is sad but kind of makes sense.

I suspect if we convert to a traditional IPython widget, variables (once created) might be shared with Python. I'll need to investigate.

With the existing API, we will be able to move data back and forth like so:

- push tree data into the illustration (eg, a Newick string)
- dump SVG output to the notebook page
- dump full illustration JSON to the notebook page, for re-use later
- read in all local variables from the notebook page, to populate the source list for trees and supplemental data
- _other ideas welcome_!

For now, other operations -- styling decisions, layout, etc. -- still happen within the Tree Illustrator UI.

**Comment by jimallman** [comment]
Here are some links related to persistent JS variables and (more importantly) sharing data between Python and Javascript in a notebook. I believe I can incorporate these ideas to get the behavior we want.

https://jakevdp.github.io/blog/2013/06/01/ipython-notebook-javascript-python-communication/

http://www.peterbouda.eu/ipython-and-javascript-interaction.html

http://stackoverflow.com/questions/28080079/can-i-create-an-ipython-notebook-using-javascript-as-the-language-in-the-cells

http://ipython.org/ipython-doc/2/api/generated/IPython.core.display.html

https://github.com/ipython-contrib/IPython-notebook-extensions/wiki

http://www.damian.oquanta.info/posts/tweet-me-said-an-ipython-notebook-cell-and-i-did-it.html

**Comment by jimallman** [comment]
As of today (43f491e) we have basic notebook integration working with "zero installation". A short Javascript snippet (using `%%javascript` magic) adds Tree Illustrator support to any live notebook. 
```%%javascript
$.getScript('http://rawgit.com/OpenTreeOfLife/tree-illustrator/43f491e/stylist/ipynb-tree-illustrator.js',
    function() { IPythonTreeIllustrator.initNotebookUI(element); } 
);
```
Running this cell will add a button to the notebook toolbar to launch the Tree Illustrator in a popup. It also creates a "home" cell that lists any illustrations currently saved in the notebook.

<img width="1160" alt="screen shot 2015-12-11 at 6 57 57 pm" src="https://cloud.githubusercontent.com/assets/446375/11758456/3aa050c8-a039-11e5-8c91-f203bfa91d74.png">

**N.B.** This only works in a live notebook (not static HTML!), since we need access to Jupyter's server-side kernel and cells and the notebook's metadata, where illustrations are stored. But it's possible (and getting easier) to dump illustration SVG to a notebook cell. 

The resulting live notebooks can be shared (via GitHub gist, etc.) complete with illustration data.
